#!/bin/bash

# override properties like:
# export environment_music_scrobbling1_baseurl="http://localhost:${RESTDRIVER_PORT:="8081"}"

. test_helper.sh
TIMEOUT=30

if [ "$1" != "wait" ]
then
    run_test ":filter integration" $TIMEOUT
else
    lein ring server-headless
fi
